# Generated by Django 5.0 on 2024-02-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacen',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen'),
        ),
    ]
