# Generated by Django 5.0 on 2024-02-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_producto_almacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.unidadmedida'),
        ),
    ]
