# Generated by Django 5.0 on 2024-02-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_remove_producto_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='almacen',
        ),
    ]
